### ISSUE TITLE
Distributions page is old style and has a bad link

### ISSUE THREAD

**Issue by dlancea** [symfony/symfony-marketing#164]
The Distributions page (http://symfony.com/distributions) is still using the old style, particularly noticable with the navbar.

Also, the Symfony CMF link is bad. It points to https://cmf.symfony.com/ but the correct URL should be http://cmf.symfony.com/. Note the http instead of https.

**Comment by javiereguiluz** [comment]
Closing this old bug report which was fixed by #165.
