### ISSUE TITLE
No explicit link to GitHub on the page

### ISSUE THREAD

**Issue by frastel** [symfony/symfony-marketing#170]
I hope this is the correct place for my issue.

I just clicked through the updated pages on symfony.com and I searched for references to the GitHub Repository and found almost nothing (besides [the contribution page](http://symfony.com/doc/current/contributing/code/patches.html). Even the footer contains no link to GitHub.

In some places the text assumes that everybody knows that the source code is hosted on GitHub. Sure, no problem for the most developers! Everybody of us knows where the source code is located. But what about beginners/starters? They are going to symfony.com, download the source code, browse the documentation, but they might not recognize that the code is provided on GitHub. Google lists the repository on the 5th place hitting the search for "symfony" so it's not that difficult to get this information. 

But why this information is not more explicitly mentioned on the page (like it is done on other product/framework homepages)?

Maybe I am completely blind and overlooked the link somewhere but at the time of writing I have not recognized an according link.

**Comment by javiereguiluz** [comment]
The Download page will soon include a link to the Symfony's source code at GitHub. Thanks for this suggestion.

**Comment by javiereguiluz** [comment]
It took us some time, but the GitHub repository is finally mentioned on http://symfony.com/download
