### ISSUE TITLE
"What is Symfony": Untranslatable blocks?

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-marketing#174]
When you view http://symfony.com/what-is-symfony in any other language than English, you'll see that there are some parts that are not translated:

* the large block quote at the top right to the Symfony logo
* the four blocks "Symfony Framework", "Symfony Components", "Symfony Community" and "Symfony Philosophy"
* the Symfony project stats
* the Symfony ecosystem

**Comment by xabbuh** [comment]
ping @fabpot @javiereguiluz

**Comment by javiereguiluz** [comment]
Closing it as fixed because the current "What is Symfony" template already allows to translate all its contents: https://github.com/symfony/symfony-marketing/blob/master/views/en/what_is_symfony.html.twig

**Comment by xabbuh** [comment]
thanks
