### ISSUE TITLE
Translations for projects are not accessible

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-marketing#182]
The homepage for projects is translated in Slovenian and German. However, the links to the different projects only link to the English version of the project description. You even cannot enter them by typing the URL manually (for example, I would have expected http://symfony.com/sl/projects/pagekit and http://symfony.com/de/projects/pagekit to work).

**Comment by xabbuh** [comment]
ping @fabpot @javiereguiluz

**Comment by javiereguiluz** [comment]
I'm going to take care of this. As you can see in #257 we're working hard to make all contents translatable, so you can expect to have this solved soon.

**Comment by xabbuh** [comment]
:+1: Thank you, Javier. I'm looking forward to it.

**Comment by xabbuh** [comment]
@javiereguiluz Do you have any news?

**Comment by javiereguiluz** [comment]
A (private) pull request has been sumitted and we could start translating project pages soon.

**Comment by OskarStark** [comment]
When will this be available?

**Comment by javiereguiluz** [comment]
Sadly, I don't know.

**Comment by OskarStark** [comment]
Ok no Problem 😉

Am Dienstag, 1. September 2015 schrieb Javier Eguiluz :

**Comment by fabpot** [comment]
Closing as we've just removed all translations.
