### ISSUE TITLE
Distributions page not showing correct title

### ISSUE THREAD

**Issue by robcaw** [symfony/symfony-marketing#223]
The distributions page (http://symfony.com/distributions) does not show the correct title, although it is correctly defined in https://github.com/symfony/symfony-marketing/blob/master/views/en/get_started/distributions.html.twig.

The response shows `<title> - Symfony</title>`, instead of what I guess should be `<title>Symfony Distributions</title>`

**Comment by javiereguiluz** [comment]
@robcaw thanks for reporting this error (and sorry for the late response). The error is now fixed and thanks to your issue, I've just updated the title from `Distributions` to `Symfony Distributions`. Besides, I've updated the templates for all translations, to match the new page design. Thanks!
