### ISSUE TITLE
Typo in The Symfony Ecosystem

### ISSUE THREAD

**Issue by khasinski** [symfony/symfony-marketing#224]
Can't find this file in the repository, but it's showing up here http://symfony.com/what-is-symfony:

The Symfony Ecosystem
These well-known PHP projects have also originated from or around Symfony project:

Silex, the PHP microframework built on top of Symfony Components
Twig, the fast, safe and **moder** PHP templating engine
Swiftmailer, the no-brainer solution to get your emails delivered

**Comment by svemir** [comment]
The typo is still there...

**Comment by jakzal** [comment]
ping @javiereguiluz

**Comment by fabpot** [comment]
fixed, will be in the next deploy.

**Comment by javiereguiluz** [comment]
Closing it as fixed. Thanks for reporting it.
