### ISSUE TITLE
Magento project

### ISSUE THREAD

**Issue by viviengaetan** [symfony/symfony-marketing#248]
Magento was removed from the list in #241.
Isn't Magento using the [console](https://github.com/magento/magento2/blob/master/composer.json#L38) component?

Should we wait for them to finish their development before adding back Magento to the project list?

**Comment by xabbuh** [comment]
FYI, it was removed because they stopped using the Yaml component. After #241 was merged, they started using the Console component in magento/magento2@e865565d901d7674a8d68568b6d84d3978507063.

**Comment by viviengaetan** [comment]
Thanks zabbuh.

I have read that and checked before opening this issue. The real question behind my idea is about: do we wait for them to be stable or do we add/remove them according to their development.

**Comment by javiereguiluz** [comment]
@viviengaetan thanks for reporting this change in Magento project. I've just created #276 to add the project back.
