### ISSUE TITLE
eZ Publish Platform 5.1 is not a Open Source

### ISSUE THREAD

**Issue by pcabreus** [symfony/symfony-marketing#253]
If someone know how I can download eZ Publish Platform 5.* free please light me. Only the eZ Publish Community is Open Source and It is not supported by eZ System. Remove or update this project by eZ Community project.

**Comment by javiereguiluz** [comment]
@pcabreus thanks for reporting this issue. Given that we only list open source projects and given the different eZ versions, I've created #279 to update the information of the eZ Project.
