### ISSUE TITLE
The support channels are not described anymore on the website

### ISSUE THREAD

**Issue by stof** [symfony/symfony-marketing#271]
the left menu of the community section contains ``Mailing lists`` and ``Forum``, which are both closed now.

And the ``Provide support`` link on http://symfony.com/community points to http://symfony.com/mailing-lists which is an empty page

Our primary support channel is now SO, but I cannot find anywhere on the website showing it.

/cc @fabpot @javiereguiluz

**Comment by javiereguiluz** [comment]
You are right. The needed changes are half-done ... but right now I'm 100% on the Symfony Profiler redesign. I'll return to this soon. Thanks!

**Comment by stof** [comment]
@javiereguiluz I tend to think that advertising our support channels rather than non-working pages has a higher priority actually
