### ISSUE TITLE
symfony showcase page 10 is not found, but shown in the pager

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony-marketing#273]
![bildschirmfoto 2015-08-17 um 10 22 43](https://cloud.githubusercontent.com/assets/995707/9300801/039b21f4-44ca-11e5-9eb3-cff7b721ba43.png)

![bildschirmfoto 2015-08-17 um 10 22 49](https://cloud.githubusercontent.com/assets/995707/9300806/085c42a4-44ca-11e5-9ec1-949ab517fe7b.png)

**Comment by javiereguiluz** [comment]
@OskarStark thanks for reporting this issue. The fix was very easy but discovering it was not. We finally have fixed it and it will be available after the next website deploy.

**Comment by OskarStark** [comment]
thank you Javier!

does the pending projects are causing this error?

Oskar

**Comment by OskarStark** [comment]
btw. the PR isn't referenced yet but the label "hasPR"

**Comment by javiereguiluz** [comment]
You are right. The "hasPR" label can be misleading. This issu has a PR ... but it's in the symfony.com private repository ;)  Sorry for the confusion, but this label helps me quickly detect which errors have been fixed.

**Comment by OskarStark** [comment]
this was just a hint ;-)

fine for me :+1:

**Comment by javiereguiluz** [comment]
The fix has been deployed.
