### ISSUE TITLE
Wrong GitHub URL for the Guard component

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-marketing#331]
The linked URL for the Guard component is https://github.com/symfony/guard while it should be https://github.com/symfony/security-guard. Maybe the code URLs are generated based on the components' names.

**Comment by OskarStark** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Closing it as fixed because http://symfony.com/components/Guard now points to https://github.com/symfony/security-guard  If the error occurs in any other page, please reopen this issue. Thanks!

**Comment by xabbuh** [comment]
Thanks Javier, looks good to me. :+1:
