### ISSUE TITLE
freepost is not using Symfony full stack.

### ISSUE THREAD

**Issue by vimishor** [symfony/symfony-marketing#354]
[freepost](http://symfony.com/projects/freepost) is listed under [Projects using Symfony](http://symfony.com/projects) as using the Symfony full stack, but looking at the [source code](https://notabug.org/zPlus/freepost) it doesn't look like it does.

Actually, after a quick look at the code, it looks like that project is using only Twig.

**Comment by RicardoJ** [comment]
Thank you for reporting this. I made a pull request where I reviewed the source code and changed the project accordingly.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #355.
