### ISSUE TITLE
Minor url inconvenience on /planet

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-marketing#364]
When visiting http://symfony.com/blog, you will get redirected to http://symfony.com/blog/. But if you visit http://symfony.com/planet/ it will 404. http://symfony.com/planet does work however, so my guess is that the route configuration is simply missing a trailing slash at the end so both would work.

I haven't tested other pages but my assumption is that it would be nice to have all routes work the same.

**Comment by javiereguiluz** [comment]
Closing it as fixed because both URLs work now: /planet and /planet/
