### ISSUE TITLE
Book feature on symfony.com

### ISSUE THREAD

**Issue by packtpartner** [symfony/symfony-marketing#368]
Hi,

Packt is proud to publish a new book on Symfony.
[Mastering Symfony](https://www.packtpub.com/web-development/mastering-symfony)

We would appreciate if you could create a Resources or Books page to feature this book on symfony.com. I think it will help many developers in their learning.

Let me know if something like this can be done.

Thanks in advance.

**Comment by Ricknox** [comment]
Currently there is no section on the website for this link. However, maybe @javiereguiluz could help out. Maybe a new section in the `marketplace`?

**Comment by fabpot** [comment]
We do not advertize books on symfony.com anywhere. And I would not want to do that without having reviewed the books we promote. So, closing for now.
