### ISSUE TITLE
HTTPS site requesting Jobs api over HTTP

### ISSUE THREAD

**Issue by lauripiisang** [symfony/symfony-marketing#371]
all.js?v=4:3 Mixed Content: The page at 'https://symfony.com/doc/current/quick_tour/the_big_picture.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://jobs.sensiolabs.com/api/random'. This request has been blocked; the content must be served over HTTPS.
send @ all.js?v=4:3
2016-12-21 16:18:02.428 all.js?v=4:3 XMLHttpRequest cannot load http://jobs.sensiolabs.com/api/random. Failed to start loading.

**Comment by javiereguiluz** [comment]
@lauripiisang thanks for reporting this issue. You are right and this must be solved. Sadly I can't provide an estimated time to solve it. Given that other people have reported this in the past and given that we have it in our TODO list, I'm closing this as duplicate. Bu thank you anyway!!

**Comment by lauripiisang** [comment]
I find it odd how marketing doesn't seem to prioritize actually showing banners for internal (probably revenue-generating?) site.

Also, in the future, if you say it's been reported before or it's some duplicate or in the TODO list, bring up references.

Good luck

**Comment by javiereguiluz** [comment]
@lauripiisang sorry, you are right. Here is the duplicated report: https://github.com/symfony/symfony-docs/issues/6682  In addition to that one, I've been notified about this personally via email, Twitter and Slack :(   I've reported this internally more than once, so I know that it will be fixed, but I can't give you a tentative fix time. I'm sorry.
