### ISSUE TITLE
Add slack channel on /support

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony-marketing#373]
The [support page](http://symfony.com/support) should also mention the Slack channel. Maybe event replace IRC?

Here is the link to the slack invite: https://slackinvite.me/to/symfony-devs

**Comment by peterkokot** [comment]
This has been mentioned also here:
https://github.com/symfony/symfony-marketing/pull/372

**Comment by Nyholm** [comment]
Thank you Peter.

**Comment by elmpp** [comment]
hi there. Am looking for a slack invite also but that site seems down. Any ideas?

**Comment by petk** [comment]
Try here:
http://symfony.com/slack-invite

**Comment by Gabb1995** [comment]
Seems like the link is down again?

**Comment by javiereguiluz** [comment]
@Gabb1995 yes! It expires every month. This is the new one which will be online at symfony.com very soon: https://join.slack.com/t/symfony-devs/shared_invite/enQtMzIwNzk5NTgwMjkwLTk4MzA0MzY5NjY5Y2MwMTE5Y2I4OWMzNWUzNjgyYTA2ZWM4ZjFkMWJjMDAyNWYxZTI1YTg3YmJkYzAwNjBkNjg
