### ISSUE TITLE
wrong docs linked for SonataAdminBundle on symfony.com

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony-marketing#385]
Hey @javiereguiluz,

maybe you could help us changing this to the right docs:
http://symfony.com/doc/current/bundles/SonataAdminBundle/index.html

this leads to `2.x` instead of `3.x`, which is the current version of sonata

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. I've moved it to https://github.com/symfony/symfony-docs/issues/7579 because that's the repository where we usually deal with website errors. I'm looking into this right now. Thanks!

**Comment by OskarStark** [comment]
Thank you!
