### ISSUE TITLE
Symfony.com's pull down has visuall isues - navigation stays no top when the menu is opened

### ISSUE THREAD

**Issue by ssaki** [symfony/symfony-marketing#395]
Reproducible on Firefox 52 && Chromium 58

There are two different cases and one of them feels a lot more "broken". Both are caused by the pull down menu haven lower z-index(9000) than the colliding nav components(9999)

1. When the the scrollbar Y is 0 header section has `z-index: auto` but `.header__nav { z-index: 9999; }`:
![pull-down-no-scroll](https://cloud.githubusercontent.com/assets/433007/26520745/fa000fa8-42e0-11e7-8c0e-da4b233d7dad.png)

2. When the page was scrolled down and the nav is static on top of the screen - both `.header__bottom` and the nav have `z-index: 9999` so it feels less broken (nav has it's background) but is still cuts-off the the letters on the first row inside the pull-down
![pull-down-scroll](https://cloud.githubusercontent.com/assets/433007/26520763/5e843756-42e1-11e7-8ec7-aee4d69ef279.png)

Increasing pull-down's z-index to 10000 seems to solve the issue
```css
#sln { z-index: 10000; }
```

P.S.
Haven't found more relevant repository to report this (and eventually to provide a patch). If that's considered to be the wrong place please close and put a repo link in the comment.
Cheers

**Comment by javiereguiluz** [comment]
@ssaki thank you very much for this bug report and for providing the solution and a great explanation. As you may notice, lately we're doing a lot of changes on symfony.com to improve/simplify things. So we may introduce some minor breaks while changing everything 😊 

I've added your fix to the private repository where the code of symfony.com is stored. Thanks!
