### ISSUE TITLE
Slack invite inactive

### ISSUE THREAD

**Issue by nplhse** [symfony/symfony-marketing#424]
I was trying to access the "[Hang on the Slack chat](https://symfony.com/slack-invite)" link on the symfony.com website but I just got an error telling me that the invite link is no longer active.

> This invite link is no longer active.
> Please check with the person who shared it with you to see if there's a new link available. 

Maybe somebody needs to create a new invite link? Or is there a way to just re-activate the existing invite?

**Comment by javiereguiluz** [comment]
Closing as fixed because we renewed the invite link. Thanks!
