### ISSUE TITLE
the slack link is not working

### ISSUE THREAD

**Issue by paulovitorbal** [symfony/symfony-marketing#435]
When I try to join the slack community I receive an error saying that the link is not active anymore.

I suggest updating the link, or, removing the slack icon from the list "follow Symfony".

**Comment by javiereguiluz** [comment]
Thanks for warning us about this. We've already updated the link and it will be online after the next deploy. If you can't wait, here's the new link: https://join.slack.com/t/symfony-devs/shared_invite/enQtMjQ2NjczMDkyMzEwLTE5OTY2MTI0ODZkMTZjNjM0MDgzN2EyOTQ4YzI5OGI1ZGE3ZDc1NWE3MTVlNjczYzU5Njk4OTNkMjEzOTA2MjI

Thanks!

**Comment by anyt** [comment]
The link is not active again.
